In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = np.array([[1,2,3],
            [4,5,6],
             [7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(a.size)
print(a.dtype)
print(B.shape)

6
int64
(3, 3)


In [6]:
type(a)

numpy.ndarray

np.empty((rows,columns),dtype)

In [7]:
x = np.empty((3,3),dtype = float)
x

array([[4.81352628e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [8]:
Y = np.empty((3,4),dtype = float)
Y

array([[6.92614123e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [6.92598206e-310, 9.34289413e+164, 1.96821309e+160,
        5.24960488e+170],
       [6.70964813e+170, 3.27485335e+179, 3.53979077e-033,
        3.38134313e-061]])

np.ones((rows, cols), dtype)

In [9]:
x = np.ones(3)
x

array([1., 1., 1.])

In [10]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
x = np.arange(1,50,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [12]:
x = x.reshape((10,5))
x

ValueError: cannot reshape array of size 25 into shape (10,5)

In [ ]:
x = x.flatten()
x

single rows and multiple columns

In [ ]:
x = x.ravel()
x

In [ ]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

In [ ]:
a[0]

In [ ]:
a[0,0]

In [ ]:
a[2:5]

In [ ]:
a[2:5,4]

In [ ]:
a[:,2:5].dtype

In [ ]:
a = np.arange(0,18).reshape((6,3))
a

In [ ]:
b = np.arange(20,38).reshape((6,3))
b

In [ ]:
a+b

np.add(a,b)

In [ ]:
a-b

In [ ]:
np.multiply(a,b)

a*b

In [ ]:
np.divide(a,b)

In [ ]:
print(a.shape)
print(b.shape)

In [ ]:
b = b.reshape((3,6))

In [ ]:
a.dot(b)

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
b.argmax()

In [ ]:
np.sum(b)

In [ ]:
np.sum(b, axis = 1)

columns

In [ ]:
np.sum(b, axis = 0)

rows

In [ ]:
np.mean(b)

In [ ]:
np.std(b)

In [ ]:
np.log(b)

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [ ]:
np.pi

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.cos(np.pi/2)


In [ ]:
np.tan(np.pi/2)

In [ ]:
np.tan(0)

In [ ]:
x = np.arange(1,11)
y = np.arange(10, 110, 10)

plt.figure(figsize = (6,6))
plt.plot(x,y)
plt.show()

In [ ]:
x = np.arange(1,11)
y = np.arange(10, 110, 10)

plt.figure(figsize = (4,4))
plt.plot(x,y, 'r--')
plt.show()

In [ ]:
x_sin = np.arange(0,2*np.pi, 0.1)
y_sin = np.sin(x_sin)

plt.figure(figsize = (4,4))
plt.plot(x_sin, y_sin)
plt.title('Sin Curve')
plt.show()

In [ ]:
plt.figure(figsize = (6,6))
plt.subplot(2,2,1)
plt.plot(x_sin, y_sin, 'r-')
plt.title('Sin Curve')

plt.subplot(2,2,2)
plt.plot(x_cos, y_cos, 'b-')
plt.title('Cos Curve')

plt.subplot(2,2,3)
plt.plot(x_tan, y_tan, 'g-')
plt.title('Tan Curve')

plt.subplot(2,2,4)
plt.plot(x_cot, y_cot, 'w-')
plt.title('Cot Curve')

plt.show()


In [ ]:
np.random.random(1)

In [ ]:
np.random.random(2)

In [ ]:
np.random.random((2,2))

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(1,10, (2,10))

In [ ]:
np.random.randint(1,10, (2,3,4))

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randn(2,2)

In [ ]:
a = 'Numpy package'
b = 'it is an kaggle notebook'

In [ ]:
np.char.add(a, b)

In [ ]:
np.char.upper(a)

In [ ]:
np.char.lower(b)

In [ ]:
np.char.split(a)

In [ ]:
np.char.replace(a, 'Numpy', 'matplotlib')

In [ ]:
np.char.center('Numpy',40,'*')